### PR TITLE
Updated Elixir version to 1.x

### PR DESCRIPTION
**Pull request by suranyami**
* Elixir version 1.x requirement now.
* Updated package structure to be more like current practice.
* Added handy dev tools: `mix_test_watch`, `dogma`, `ex_unit_notifier`.
* Ran `dogma` linter over code and cleaned up as suggested.

### CODE REVIEW

**Comment by suranyami** [comment]
If you're okay with these changes, I'll publish the package up to hex.pm.

**Comment by suranyami** [comment]
Ah, so I tried to publish to hex.pm, but apparently, I'm not registered as an owner on their. I think you'll need to add me by running:

```bash
mix hex.owner add hexate david.parry@suranyami.com
```

When you get a chance, that'd be appreciated.

**Comment by rjsamson** [comment]
Sure - I added you.

**Comment by suranyami** [comment]
Thanks! All updated and published.

**Pull request merged**
