### PR TITLE
Warning cleanup

### PR DESCRIPTION
**Pull request by cgorshing**
Tried to clean up a few warnings I was seeing. Minor.

### CODE REVIEW

**Comment by cgorshing** [comment]
My bad - corrected failing tests I didn't even notice.

**Comment by rjsamson** [comment]
Cool! Thanks @cgorshing!

**Comment by cgorshing** [comment]
I just noticed that mix.exs states Elixir 1.3, I'm not sure if my changes work with 1.3 or not.

**Comment by rjsamson** [comment]
Yeah - it needs to get bumped - I'll do that when I bump the version for the lib in a few min

**Pull request merged**
